import { expect, test } from '@playwright/test'

test('brinde aparece no carrinho e é estornado ao voltar', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Cenário guiado').selectOption('gift')
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('button', { name: /Ir para pagamento/ }).click()
  await page.getByRole('button', { name: /Escolher benefício/ }).click()
  await page.getByRole('button', { name: /Caneca BonifiQ de brinde/ }).click()
  await page.getByRole('button', { name: 'Confirmar e resgatar' }).click()
  const token = await page.locator('.received-token strong').last().textContent()
  await page.getByLabel('Código de validação').fill(token || '')
  await page.getByRole('button', { name: 'Validar' }).click()
  await expect(page.getByText('Benefício aplicado')).toBeVisible()
  await expect(page.getByText('Caneca BonifiQ', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Editar seleção/ }).click()
  await expect(page.getByText('Caneca BonifiQ', { exact: true })).toHaveCount(0)
})

test('cenário sem OTP resgata e registra pedido com trace', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Cenário guiado').selectOption('no-validation')
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('button', { name: /Ir para pagamento/ }).click()
  await page.getByRole('button', { name: /Escolher benefício/ }).click()
  await page.getByRole('button', { name: /R\$10,00 de desconto/ }).click()
  await page.getByRole('button', { name: 'Confirmar e resgatar' }).click()
  await expect(page.getByRole('heading', { name: /Validação de identidade/ })).toHaveCount(0)
  await expect(page.getByText('Benefício aplicado')).toBeVisible()
  await page.getByRole('button', { name: /Finalizar venda em dinheiro/ }).click()
  await expect(page.getByText('Venda concluída!')).toBeVisible()
  await expect(page.getByText('Cashback ganho nesta venda')).toBeVisible()
  await expect(page.locator('.cashback-earned')).toContainText(/R\$\s*11,99/)
  await expect(page.getByText(/Nova venda em/)).toHaveCount(0)
  await page.getByRole('button', { name: /Ver integração/ }).click()
  await expect(page.getByText('POST /POS/orders', { exact: true })).toBeVisible()
  const orderTrace = page.locator('.trace-event').filter({ hasText: 'Registrar pedido' })
  await orderTrace.locator('.trace-summary').click()
  const requestBody = orderTrace.locator('pre').first()
  await expect(requestBody).toContainText('"OrderTotal"')
  await expect(requestBody).not.toContainText('"orderTotal"')
  await expect(requestBody).toContainText('98765432100')
})

test('abandono antes do redeem aparece como evento local', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Cenário guiado').selectOption('gift')
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('button', { name: /Ir para pagamento/ }).click()
  await page.getByRole('button', { name: /Escolher benefício/ }).click()
  await page.getByRole('button', { name: /Caneca BonifiQ de brinde/ }).click()
  await page.getByRole('button', { name: 'Confirmar e resgatar' }).click()
  await page.getByRole('button', { name: 'Abandonar resgate' }).click()
  await page.getByRole('button', { name: /Ver integração/ }).click()
  await expect(page.getByText('EVENTO LOCAL · sem chamada à API', { exact: true })).toBeVisible()
  await expect(page.getByText('Resgate abandonado', { exact: true })).toBeVisible()
  await expect(page.getByText(/DELETE \/POS\/rewards\//)).toHaveCount(0)
})

test('cancelamento parcial envia produtos e valor com o casing do contrato', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Cenário guiado').selectOption('no-rewards')
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('button', { name: /Calça Jeans/ }).click()
  await page.getByRole('button', { name: /Ir para pagamento/ }).click()
  await page.getByRole('button', { name: /Finalizar venda em dinheiro/ }).click()

  await page.getByLabel('Quantidade de Calça Jeans para cancelar').fill('1')
  await page.getByRole('button', { name: 'Cancelar itens selecionados' }).click()
  await expect(page.getByText('Cancelamento parcial enviado para a BonifiQ.')).toBeVisible()
  await expect(page.getByText('Parcialmente cancelado')).toBeVisible()
  await expect(page.getByText('Cashback ganho nesta venda')).toHaveCount(0)

  await page.getByRole('button', { name: /Ver integração/ }).click()
  const trace = page.locator('.trace-event').filter({ hasText: 'Cancelar parcialmente' })
  await trace.locator('.trace-summary').click()
  const requestBody = trace.locator('pre').first()
  await expect(requestBody).toContainText('"ValueToRefund"')
  await expect(requestBody).toContainText('"CancelKey"')
  await expect(requestBody).toContainText('"Products"')
  await expect(requestBody).toContainText('"OriginalId"')
  await expect(requestBody).not.toContainText('"valueToRefund"')
})

test('confirmação permite cancelar o pedido inteiro', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Cenário guiado').selectOption('no-rewards')
  await page.getByRole('button', { name: 'OK' }).click()
  await page.getByRole('button', { name: /Ir para pagamento/ }).click()
  await page.getByRole('button', { name: /Finalizar venda em dinheiro/ }).click()

  await page.getByRole('button', { name: 'Cancelar pedido inteiro' }).click()

  await expect(page.getByRole('heading', { name: 'Pedido cancelado' })).toBeVisible()
  await expect(page.getByText('Cancelamento enviado para a BonifiQ.')).toBeVisible()
  await expect(page.getByText('Cashback ganho nesta venda')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Cancelar pedido inteiro' })).toBeDisabled()
})
